apiVersion: v1
kind: pod
metadata:
  name: roboshop
  namespace: roboshop
labels:
  project: roboshop
  environment: dev
  purpose: poc
annotations:
  imageregistry: "https://hub.docker.com"
  jenkinsURL: "http://jenkins.roboshop.com"
spec:
   containers:
      name: nginx
      image: nginx
      ports:
      - containerPort: 80